# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-25 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('father_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('pin_number', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('dob', models.CharField(default=datetime.date.today, max_length=10)),
                ('image', models.ImageField(default=b'media/user_images/icon.png', upload_to=b'media/user_images/')),
                ('salary_slip', models.FileField(default=b'media/user_images/icon.png', upload_to=b'media/user_file/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('mock_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.ForeignKey(db_column=b'UserIdList.user_id', on_delete=django.db.models.deletion.CASCADE, to='home.UserIdList'),
        ),
    ]
